orbs:
  node: circleci/node@4.5.0

version: 2.1

workflows:
  deploy:
    jobs:
      - create_release

jobs:
  create_release:
    executor:
      name: node/default
      tag: 14.17.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a8:28:9e:35:af:4f:7e:e7:3c:05:97:cd:ed:4e:64:2d"
      - checkout
      - node/install-packages
      - run:
          command: git config --global user.email circleci@circleci && git config --global user.name CircleCI
          name: set git commiter
      - run:
          command: npm ci
          name: install
      - run:
          command: npx lerna bootstrap
          name: bootstrap
      - run:
          command: npx lerna run build
          name: build
      - run:
          command: npm run create-release
          name: create_release
