orbs:
  node: circleci/node@4.5.0

version: 2.1

workflows:
  lerna_deploy:
    jobs:
      - approve:
          type: approval
      - lerna_create_release:
          requires:
            - approve
  nx_deploy:
    jobs:
      - approve:
          type: approval
      - nx_create_release:
          requires:
            - approve

jobs:
  lerna_create_release:
    executor:
      name: node/default
      tag: 16.14.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a8:28:9e:35:af:4f:7e:e7:3c:05:97:cd:ed:4e:64:2d"
      - checkout
      - node/install-packages
      - run:
          command: git config --global user.email circleci@circleci && git config --global user.name CircleCI
          name: set git commiter
      - run:
          command: npm ci
          name: install
      - run:
          command: npx lerna run build
          name: build
      - run:
          command: npx lerna run release
          name: create_release
  nx_create_release:
    executor:
      name: node/default
      tag: 16.14.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a8:28:9e:35:af:4f:7e:e7:3c:05:97:cd:ed:4e:64:2d"
      - checkout
      - node/install-packages
      - run:
          command: git config --global user.email circleci@circleci && git config --global user.name CircleCI
          name: set git commiter
      - run:
          command: npm ci
          name: install
      - run:
          command: npx nx run-many --target=build --all
          name: build
      - run:
          command: npx nx run-many --target=release --all
          name: create_release
